import { writeFileSync, existsSync } from 'fs';
import { join } from 'path';

function generateSecret(length = 64) {
  const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
  const bytes = new Uint8Array(length);
  crypto.getRandomValues(bytes);
  return Array.from(bytes, b => chars[b % chars.length]).join('');
}

const target = join(process.cwd(), '.dev.vars');

if (existsSync(target)) {
  console.log('.dev.vars already exists. Delete it first or run with --force to overwrite.');
  if (!process.argv.includes('--force')) process.exit(0);
}

const content = `# Vexioriq API — Local Development Environment Variables
# Auto-generated by scripts/generate-env.js

# HMAC secret for API key hashing
API_KEY_HMAC_SECRET=${generateSecret(64)}

# Internal sync secret for Vercel -> API key registration
INTERNAL_SYNC_SECRET=${generateSecret(48)}

# CORS origins (comma-separated)
CORS_ORIGINS=http://localhost:3000,https://vexioriq.com
`;

writeFileSync(target, content, 'utf-8');
console.log('.dev.vars generated with secure random secrets.');
